"""create sender_accounts table

Revision ID: b32f79997836
Revises: bbb782353de4
Create Date: 2026-07-20 18:28:19.701844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32f79997836'
down_revision: Union[str, Sequence[str], None] = 'bbb782353de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_status_enum = sa.Enum('ACTIVE', 'INACTIVE', name='accountstatus')
    op.create_table('sender_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.String(length=255), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('hourly_limit', sa.Integer(), nullable=False),
    sa.Column('email_sent_hour', sa.Integer(), nullable=False),
    sa.Column('status', account_status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_sender_account_id'), 'sender_account', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sender_account_id'), table_name='sender_account')
    op.drop_table('sender_account')
    op.execute('DROP TYPE IF EXISTS accountstatus')
    # ### end Alembic commands ###
