"""add user_id to html_templates

Revision ID: a02ecaf9956d
Revises: a4ab25a11bfc
Create Date: 2026-08-25 19:42:18.062209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02ecaf9956d'
down_revision: Union[str, Sequence[str], None] = 'a4ab25a11bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('email_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('html_templates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'html_templates', 'users', ['user_id'], ['id'])
    op.add_column('sender_accounts', sa.Column('emails_sent_hour', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('uploads', sa.Column('error_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'error_message')
    op.drop_column('uploads', 'mime_type')
    op.drop_column('uploads', 'file_size')
    op.drop_column('sender_accounts', 'emails_sent_hour')
    op.drop_constraint(None, 'html_templates', type_='foreignkey')
    op.drop_column('html_templates', 'user_id')
    op.drop_column('email_logs', 'updated_at')
    op.drop_column('email_logs', 'created_at')
    # ### end Alembic commands ###
